DROP TABLE IF EXISTS TimberFleet_Contadores;
DROP TABLE IF EXISTS TimberFleet_Apontamentos;
DROP TABLE IF EXISTS TimberFleet_Formulario;
DROP TABLE IF EXISTS TimberFleet_Localizacao;
DROP TABLE IF EXISTS TimberFleet_Producao;
DROP TABLE IF EXISTS TimberFleet_Produtos_producao;

CREATE TABLE TimberFleet_Contadores (
	id_interno int IDENTITY(1,1) NOT NULL UNIQUE,
	id_ident nvarchar(100) NOT NULL,
	prefixo nvarchar(8) NOT NULL,
	nome_operador nvarchar(100),
	data_contadores datetime NOT NULL,
	operacao_status nvarchar(30),
	odometro_motor float(53) NOT NULL,
	odometro_operacao float(53) NOT NULL,
	odometro_implemento float(53) NOT NULL,
	odometro_rodante float(53) NOT NULL,
	horimetro_motor float(53) NOT NULL,
	horimetro_operacao float(53) NOT NULL,
	horimetro_implemento float(53) NOT NULL,
	horimetro_rodante float(53) NOT NULL,
	ativacao_motor int NOT NULL,
	ativacao_operacao int NOT NULL,
	ativacao_implemento int NOT NULL,
	ativacao_rodante int NOT NULL,
	tempo_movimentacao_motor float(53) NOT NULL,
	tempo_movimentacao_operacao float(53) NOT NULL,
	tempo_movimentacao_implemento float(53) NOT NULL,
	tempo_movimentacao_rodante float(53) NOT NULL,
	diferenca_odometro_motor FLOAT(53) NOT NULL,
	diferenca_odometro_operacao FLOAT(53) NOT NULL,
	diferenca_odometro_implemento FLOAT(53) NOT NULL,
	diferenca_odometro_rodante FLOAT(53) NOT NULL,
	diferenca_horimetro_motor FLOAT(53) NOT NULL,
	diferenca_horimetro_operacao FLOAT(53) NOT NULL,
	diferenca_horimetro_implemento FLOAT(53) NOT NULL,
	diferenca_horimetro_rodante FLOAT(53) NOT NULL,
	diferenca_ativacao_motor INT NOT NULL,
	diferenca_ativacao_operacao INT NOT NULL,
	diferenca_ativacao_implemento INT NOT NULL,
	diferenca_ativacao_rodante INT NOT NULL,
	diferenca_tempo_movimentacao_motor FLOAT(53) NOT NULL,
	diferenca_tempo_movimentacao_operacao FLOAT(53) NOT NULL,
	diferenca_tempo_movimentacao_implemento FLOAT(53) NOT NULL,
	diferenca_tempo_movimentacao_rodante FLOAT(53) NOT NULL,
	data_registro date NOT NULL,
	PRIMARY KEY (id_interno)
);

CREATE TABLE TimberFleet_Formulario (
	id_interno int IDENTITY(1,1) NOT NULL UNIQUE,
	id_ident nvarchar(100) NOT NULL,
	prefixo nvarchar(8) NOT NULL,
	data_formulario datetime NOT NULL,
	nome_operador nvarchar(100),
	codigo_operador smallint NOT NULL,
	operacao_status nvarchar(30),
	titulo_formulario nvarchar(100) NOT NULL,
	matricula_operador smallint,
	matricula_comboista smallint,
	matricula_mecanico smallint,
	tipo_falha nvarchar(50),
	atividade_anterior_apropriacao nvarchar(50),
	tipo_avaliacao nvarchar(20),
	avaliacao nvarchar(MAX),
	equipamento_disponivel nvarchar(10),
	motivo_indisponibilidade nvarchar(100),
	horimetro_motor int,
	tipo_oleo nvarchar(100),
	quantidade_abastecida smallint,
	tipo_produto nvarchar(50),
	volume_carga_caminhao nvarchar(20),
	frota_caminhao nvarchar(10),
	balanca int,
	box_descarga int,
	motivo nvarchar(100),
	status_inicio_abastecimento nvarchar(100),
	tipo_operacao nvarchar(100),
	talhao_operacao nvarchar(30),
	tipo_produto nvarchar(50),
	quantidade_arvores_cortadas smallint,
	informe_producao smallint,
	volume_caixa_carga nvarchar(20),
	tipo_servico nvarchar(50),
	quantidade_toco smallint,
	hectares nvarchar(50),
	parada nvarchar(50),
	data_registro date NOT NULL,
	PRIMARY KEY (id_interno)
);

CREATE TABLE TimberFleet_Localizacao (
	id_interno int IDENTITY(1,1) NOT NULL UNIQUE,
	id_ident nvarchar(100) NOT NULL,
	nome_operador nvarchar(30),
	prefixo nvarchar(8) NOT NULL,
	data_localizacao datetime NOT NULL,
	latitude float(53) NOT NULL,
	longitude float(53) NOT NULL,
	operacao_status nvarchar(30),
	data_registro date NOT NULL,
	PRIMARY KEY (id_interno)
);

CREATE TABLE TimberFleet_Apontamentos (
	id_interno int IDENTITY(1,1) NOT NULL UNIQUE,
	id_ident nvarchar(100) NOT NULL,
	prefixo nvarchar(8) NOT NULL,
	nome_operador nvarchar(100),
	codigo_operador smallint NOT NULL,
	data_inicio datetime NOT NULL,
	data_final datetime NOT NULL,
	inicio_horimetro_motor float(53) NOT NULL,
	final_horimetro_motor float(53) NOT NULL,
	operacao_status nvarchar(30),
	titulo_formulario nvarchar(100) NOT NULL,
	matricula_operador smallint,
	matricula_comboista smallint,
	matricula_mecanico smallint,
	tipo_falha nvarchar(50),
	atividade_anterior_apropriacao nvarchar(50),
	tipo_avaliacao nvarchar(20),
	avaliacao nvarchar(MAX),
	equipamento_disponivel nvarchar(10),
	motivo_indisponibilidade nvarchar(100),
	horimetro_motor int,
	tipo_oleo nvarchar(100),
	quantidade_abastecida smallint,
	tipo_produto nvarchar(50),
	volume_carga_caminhao nvarchar(20),
	frota_caminhao nvarchar(10),
	balanca int,
	box_descarga int,
	motivo nvarchar(100),
	status_inicio_abastecimento nvarchar(100),
	tipo_operacao nvarchar(100),
	talhao_operacao nvarchar(30),
	tipo_produto nvarchar(50),
	quantidade_arvores_cortadas smallint,
	informe_producao smallint,
	volume_caixa_carga nvarchar(20),
	tipo_servico nvarchar(50),
	quantidade_toco smallint,
	hectares nvarchar(50),
	parada nvarchar(50),
	data_registro date NOT NULL,
	PRIMARY KEY (id_interno)
);

CREATE TABLE TimberFleet_Producao (
	id_interno int IDENTITY(1,1) NOT NULL UNIQUE,
	id_ident nvarchar(100) NOT NULL,
	tipo_arquivo nvarchar(3) NOT NULL,
	prefixo nvarchar(8) NOT NULL,
	nome_operador nvarchar(100) NOT NULL,
	data_producao datetime NOT NULL,
	contagem_arvores smallint NOT NULL,
	volume_total float(53),
	data_registro date NOT NULL,
	PRIMARY KEY (id_interno)
);

CREATE TABLE TimberFleet_Produtos_producao (
	id_interno int IDENTITY(1,1) NOT NULL UNIQUE,
	id_ident nvarchar(100) NOT NULL,
	prefixo nvarchar(8) NOT NULL,
	data_producao datetime NOT NULL,
	quantidade_toras smallint,
	volume_toras float(53),
	comprimento_minimo smallint NOT NULL,
	comprimento_maximo smallint NOT NULL,
	comprimento_medio float(53) NOT NULL,
	data_registro date NOT NULL,
	PRIMARY KEY (id_interno)
);